import Link from "next/link";
import { ArrowIcon, GameIcon, LockIcon, PlayIcon } from "@/components/icons";

export default function HomePage() {
  return <>
    <section className="container grid min-h-[68vh] items-center gap-10 py-16 lg:grid-cols-[1.15fr_.85fr]">
      <div><p className="eyebrow">Gaming accounts · OTT access</p><h1 className="title-xl mt-5 max-w-4xl">Digital access, handled like a real order.</h1><p className="muted mt-6 max-w-2xl text-base leading-7 sm:text-lg">Digital Buy sells configurable gaming account access and subscription products. Payments are submitted by bKash or Nagad, reviewed by an administrator, then delivered securely inside your account.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn btn-primary" href="/gaming">Browse gaming <ArrowIcon/></Link><Link className="btn btn-secondary" href="/ott">Browse OTT</Link></div></div>
      <div className="surface relative overflow-hidden p-6 sm:p-8"><div className="absolute right-0 top-0 h-40 w-40 bg-sky-400/10 blur-3xl"/><p className="eyebrow">How ordering works</p><div className="mt-7 space-y-5">{[["01","Choose a product","See the current price, duration and availability from the live catalog."],["02","Submit payment","Pay using the displayed bKash or Nagad instructions and submit the transaction reference."],["03","Admin verification","Payment stays marked as submitted until an administrator verifies it."],["04","Secure delivery","Completed order credentials and instructions appear only inside your authenticated order history."]].map(([n,t,b])=><div key={n} className="grid grid-cols-[42px_1fr] gap-3"><span className="font-black text-sky-300">{n}</span><div><h2 className="font-extrabold">{t}</h2><p className="muted mt-1 text-sm leading-6">{b}</p></div></div>)}</div></div>
    </section>
    <section className="container py-8"><div className="mb-7"><p className="eyebrow">Store</p><h2 className="title-lg mt-3">Choose a category</h2></div><div className="grid gap-4 md:grid-cols-3">
      <Link href="/gaming" className="card group min-h-64 p-7 transition hover:-translate-y-1 hover:border-sky-500/50"><GameIcon className="h-8 w-8 text-sky-300"/><h3 className="mt-12 text-2xl font-black">Gaming</h3><p className="muted mt-2 text-sm leading-6">Shared rentals and personal account products for Steam, Xbox and Ubisoft.</p><div className="mt-6 flex items-center gap-2 font-extrabold text-sky-300">Explore gaming <ArrowIcon/></div></Link>
      <Link href="/ott" className="card group min-h-64 p-7 transition hover:-translate-y-1 hover:border-emerald-500/50"><PlayIcon className="h-8 w-8 text-emerald-300"/><h3 className="mt-12 text-2xl font-black">OTT</h3><p className="muted mt-2 text-sm leading-6">Shared and personal duration-based subscription products across configurable platforms.</p><div className="mt-6 flex items-center gap-2 font-extrabold text-emerald-300">Explore subscriptions <ArrowIcon/></div></Link>
      <div className="card min-h-64 p-7 opacity-75" aria-disabled="true"><LockIcon className="h-8 w-8 text-amber-300"/><div className="mt-12 flex items-center gap-3"><h3 className="text-2xl font-black">Top Up</h3><span className="badge text-amber-300">Coming Soon</span></div><p className="muted mt-2 text-sm leading-6">Top-up products are locked until the service is ready for live fulfillment.</p></div>
    </div></section>
  </>;
}
