"use client";
import { useActionState } from "react";
import { reviewPaymentAction, updateOrderStatusAction, deliverCredentialsAction } from "@/lib/actions/admin-actions";
import { ActionFeedback, type ActionState } from "@/components/action-feedback";
import { SubmitButton } from "@/components/submit-button";

export function PaymentReview({ orderId }: { orderId:string }) { const [state,action]=useActionState(reviewPaymentAction,{} as ActionState); return <form action={action} className="card p-5"><ActionFeedback state={state}/><input type="hidden" name="orderId" value={orderId}/><h3 className="font-black">Payment review</h3><div className="mt-4"><label className="label" htmlFor="reason">Reason when rejecting</label><input className="input" id="reason" name="reason" maxLength={500}/></div><div className="mt-4 flex flex-wrap gap-2"><button className="btn btn-primary" name="decision" value="approve" type="submit">Verify payment</button><button className="btn btn-danger" name="decision" value="reject" type="submit">Reject payment</button></div></form> }

export function StatusControl({ orderId, current }: { orderId:string; current:string }) { const [state,action]=useActionState(updateOrderStatusAction,{} as ActionState); const terminal=["completed","failed","cancelled"].includes(current); return <form action={action} className="card p-5"><ActionFeedback state={state}/><input type="hidden" name="orderId" value={orderId}/><h3 className="font-black">Order status</h3><p className="muted mt-1 text-xs">Current: {current.replaceAll("_"," ")}</p><div className="mt-4"><label className="label" htmlFor="status">Next status</label><select className="select" id="status" name="status" disabled={terminal} required><option value="processing">Processing</option><option value="completed">Completed</option><option value="failed">Failed</option><option value="cancelled">Cancelled</option></select></div><div className="mt-4"><label className="label" htmlFor="status-reason">Reason for failed/cancelled</label><input className="input" id="status-reason" name="reason" maxLength={500}/></div><SubmitButton className="btn btn-secondary mt-4" pendingText="Updating..." disabled={terminal}>Update status</SubmitButton></form> }

export function DeliveryControl({ orderId, itemId }: { orderId:string; itemId:string }) { const [state,action]=useActionState(deliverCredentialsAction,{} as ActionState); return <form action={action} className="card p-5"><ActionFeedback state={state}/><input type="hidden" name="orderId" value={orderId}/><input type="hidden" name="orderItemId" value={itemId}/><h3 className="font-black">Encrypted delivery</h3><p className="muted mt-1 text-xs">Saved values are encrypted before database storage.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><div><label className="label" htmlFor={`u-${itemId}`}>Username / email</label><input className="input" id={`u-${itemId}`} name="username" autoComplete="off" maxLength={500}/></div><div><label className="label" htmlFor={`p-${itemId}`}>Password</label><input className="input" id={`p-${itemId}`} name="password" autoComplete="new-password" maxLength={1000}/></div></div><div className="mt-4"><label className="label" htmlFor={`i-${itemId}`}>Instructions</label><textarea className="textarea min-h-28" id={`i-${itemId}`} name="instructions" maxLength={5000}/></div><SubmitButton className="btn btn-primary mt-4" pendingText="Encrypting and saving...">Save delivery</SubmitButton></form> }
