"use client";
import { useActionState, useState } from "react";
import { submitOrderAction } from "@/lib/actions/order-actions";
import { SubmitButton } from "@/components/submit-button";
import { ActionFeedback, type ActionState } from "@/components/action-feedback";
import { money } from "@/lib/format";

export function CheckoutForm({ productId, productName, price, customerName, email, bkash, nagad }: { productId:string; productName:string; price:number; customerName:string; email:string; bkash?:string; nagad?:string }) {
  const [state, action] = useActionState(submitOrderAction, {} as ActionState);
  const [method, setMethod] = useState<"bkash"|"nagad">("bkash");
  const destination = method === "bkash" ? bkash : nagad;
  const configured = Boolean(destination);
  return <form action={action} className="space-y-7"><ActionFeedback state={state}/><input type="hidden" name="productId" value={productId}/>
    <section><p className="eyebrow">1 · Product summary</p><div className="card mt-3 flex items-center justify-between gap-4 p-4"><div><h2 className="font-black">{productName}</h2><p className="muted mt-1 text-xs">One digital product per order</p></div><div className="text-lg font-black">{money(price)}</div></div></section>
    <section><p className="eyebrow">2 · Customer information</p><div className="mt-3 grid gap-4 sm:grid-cols-2"><div><label className="label">Name</label><input className="input" value={customerName} readOnly aria-readonly="true"/></div><div><label className="label">Verified email</label><input className="input" value={email} readOnly aria-readonly="true"/></div></div></section>
    <section><p className="eyebrow">3 · Payment method</p><div className="mt-3 grid grid-cols-2 gap-3"><label className={`card cursor-pointer p-4 ${method === "bkash" ? "border-sky-500" : ""}`}><input className="mr-2" type="radio" name="paymentMethod" value="bkash" checked={method === "bkash"} onChange={()=>setMethod("bkash")}/> <strong>bKash</strong></label><label className={`card cursor-pointer p-4 ${method === "nagad" ? "border-sky-500" : ""}`}><input className="mr-2" type="radio" name="paymentMethod" value="nagad" checked={method === "nagad"} onChange={()=>setMethod("nagad")}/> <strong>Nagad</strong></label></div></section>
    <section><p className="eyebrow">4 · Payment instructions</p><div className="card mt-3 p-5">{configured ? <><p className="text-sm leading-6">Send exactly <strong>{money(price)}</strong> to the {method === "bkash" ? "bKash" : "Nagad"} number below using the payment type instructed by Digital Buy.</p><div className="mt-4 border border-slate-700 bg-slate-950 p-4 font-mono text-lg font-black tracking-wider">{destination}</div><p className="muted mt-3 text-xs leading-5">After paying, enter the mobile number used for payment and the provider transaction/reference ID. Submission does not mean automatic verification.</p></> : <p className="text-sm text-amber-200">This payment method is not configured yet. An administrator must add its merchant number in Vercel environment variables before checkout can be used.</p>}</div></section>
    <section><p className="eyebrow">5 · Payment reference</p><div className="mt-3 grid gap-4 sm:grid-cols-2"><div><label className="label" htmlFor="payerNumber">Number used to pay</label><input className="input" id="payerNumber" name="payerNumber" inputMode="numeric" pattern="01[3-9][0-9]{8}" placeholder="01XXXXXXXXX" required/></div><div><label className="label" htmlFor="reference">Transaction / reference ID</label><input className="input" id="reference" name="reference" autoComplete="off" minLength={4} maxLength={100} required/></div></div><label className="mt-4 flex items-start gap-3 text-sm text-slate-300"><input className="mt-1" type="checkbox" name="confirmPaid" required/><span>I confirm that I sent the displayed amount and that the payment reference is accurate.</span></label></section>
    <section><p className="eyebrow">6 · Submit order</p><p className="muted mt-2 text-sm leading-6">Your order will enter <strong>Payment Submitted</strong> status. It can only move forward after manual verification.</p><SubmitButton className="btn btn-primary mt-4 w-full" pendingText="Submitting order..." disabled={!configured}>Submit order for verification</SubmitButton></section>
  </form>;
}
