export const metadata = { title: "My Orders", robots: { index: false, follow: false } };
import { requireUser } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { decryptSecret } from "@/lib/crypto";
import { money } from "@/lib/format";
import { EmptyState } from "@/components/empty-state";
import { CredentialCard } from "@/components/credential-card";

export default async function OrdersPage({ searchParams }: { searchParams: Promise<{created?:string}> }) {
  const user = await requireUser(); const params = await searchParams; const supabase = await createClient();
  const { data: orders, error } = await supabase.from("orders").select("id,order_number,total_bdt,status,failure_reason,created_at,order_items(id,product_name,duration_label),payments(method,reference,status)").eq("user_id",user.id).order("created_at",{ascending:false});
  if (error) throw new Error("Could not load orders");
  const completed = (orders||[]).filter(o=>o.status==="completed"); const active=(orders||[]).filter(o=>["pending","payment_submitted","confirmed","processing"].includes(o.status)); const closed=(orders||[]).filter(o=>["failed","cancelled"].includes(o.status));
  const itemIds = completed.flatMap(o=>(o.order_items||[]).map(i=>i.id)); const credentialMap = new Map<string,{username:string|null;password:string|null;instructions:string|null}>();
  if (itemIds.length) { const admin=createAdminClient(); const {data:creds}=await admin.from("delivered_credentials").select("order_item_id,username_encrypted,password_encrypted,instructions_encrypted").in("order_item_id",itemIds); for (const c of creds||[]) credentialMap.set(c.order_item_id,{username:decryptSecret(c.username_encrypted),password:decryptSecret(c.password_encrypted),instructions:decryptSecret(c.instructions_encrypted)}); }
  const Card=({o,showCreds=false}:{o:any;showCreds?:boolean})=><article className="card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-extrabold uppercase tracking-wider text-slate-500">{o.order_number}</p><h3 className="mt-1 text-lg font-black">{o.order_items?.[0]?.product_name || "Digital product"}</h3></div><span className="badge text-sky-300">{String(o.status).replaceAll("_"," ")}</span></div><dl className="mt-4 grid grid-cols-2 gap-4 text-sm sm:grid-cols-4"><div><dt className="muted">Amount</dt><dd className="mt-1 font-bold">{money(o.total_bdt)}</dd></div><div><dt className="muted">Date</dt><dd className="mt-1 font-bold">{new Date(o.created_at).toLocaleDateString("en-BD")}</dd></div><div><dt className="muted">Duration</dt><dd className="mt-1 font-bold">{o.order_items?.[0]?.duration_label || "-"}</dd></div><div><dt className="muted">Payment</dt><dd className="mt-1 font-bold capitalize">{o.payments?.[0]?.method || "-"}</dd></div></dl>{o.failure_reason && <p className="mt-4 border border-red-900 bg-red-950/30 p-3 text-sm text-red-200">{o.failure_reason}</p>}{showCreds && o.order_items?.map((i:any)=>{const c=credentialMap.get(i.id); return c ? <CredentialCard key={i.id} {...c}/> : <p key={i.id} className="muted mt-4 text-sm">No credentials are attached to this completed item. Contact Support if delivery should include credentials.</p>;})}</article>;
  return <div className="container py-14"><p className="eyebrow">Account</p><h1 className="title-lg mt-3">My Orders</h1>{params.created && <div className="mt-6 border border-emerald-800 bg-emerald-950/30 p-4 text-sm text-emerald-100">Order {params.created} was submitted. Payment is awaiting manual verification.</div>}<section className="mt-10"><h2 className="text-xl font-black">Pending & processing</h2><div className="mt-4 grid gap-4">{active.map(o=><Card key={o.id} o={o}/>)}</div>{!active.length&&<div className="mt-4"><EmptyState title="No active orders" body="New orders and payment submissions will appear here while they are being reviewed and fulfilled."/></div>}</section><section className="mt-12"><h2 className="text-xl font-black">Completed</h2><div className="mt-4 grid gap-4">{completed.map(o=><Card key={o.id} o={o} showCreds/>)}</div>{!completed.length&&<div className="mt-4"><EmptyState title="No completed orders" body="Delivered products will appear here with protected credentials or instructions when applicable."/></div>}</section><section className="mt-12"><h2 className="text-xl font-black">Failed & cancelled</h2><div className="mt-4 grid gap-4">{closed.map(o=><Card key={o.id} o={o}/>)}</div>{!closed.length&&<div className="mt-4"><EmptyState title="No failed or cancelled orders" body="Orders that cannot be completed will remain visible here with the recorded reason where applicable."/></div>}</section></div>;
}
