import Link from "next/link";
import { requireAdmin } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { money } from "@/lib/format";
import { EmptyState } from "@/components/empty-state";

export default async function AdminOrders({searchParams}:{searchParams:Promise<{q?:string;status?:string;page?:string}>}){
  await requireAdmin(); const p=await searchParams; const page=Math.max(1,Number(p.page)||1); const perPage=50; const admin=createAdminClient();
  const safeQ=(p.q||"").replace(/[^a-zA-Z0-9 _-]/g,"").trim().slice(0,40); let relatedIds:string[]=[];
  if(safeQ){ const [paymentHits,itemHits]=await Promise.all([admin.from("payments").select("order_id").ilike("reference",`%${safeQ}%`).limit(100),admin.from("order_items").select("order_id").ilike("product_name",`%${safeQ}%`).limit(100)]); relatedIds=[...new Set([...(paymentHits.data||[]).map(x=>x.order_id),...(itemHits.data||[]).map(x=>x.order_id)])]; }
  let q=admin.from("orders").select("id,order_number,user_id,total_bdt,status,created_at,order_items(product_name),payments(method,reference,status)",{count:"exact"}).order("created_at",{ascending:false});
  if(p.status) q=q.eq("status",p.status);
  if(safeQ){ const filters=[`order_number.ilike.%${safeQ}%`]; if(relatedIds.length) filters.push(`id.in.(${relatedIds.join(",")})`); q=q.or(filters.join(",")); }
  const from=(page-1)*perPage; const{data:orders,error,count}=await q.range(from,from+perPage-1); if(error)throw new Error(error.message); const total=count||0;
  return <div><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-black">Orders</h2><p className="muted mt-1 text-sm">Search order numbers, product names and payment references.</p></div><form className="flex flex-wrap gap-2"><input className="input !w-64" name="q" defaultValue={p.q} placeholder="Order / product / payment ref"/><select className="select !w-52" name="status" defaultValue={p.status||""}><option value="">All statuses</option>{["pending","payment_submitted","confirmed","processing","completed","failed","cancelled"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><button className="btn btn-primary" type="submit">Filter</button></form></div><div className="mt-6 overflow-x-auto border border-slate-800"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-slate-950 text-xs uppercase tracking-wider text-slate-400"><tr><th className="p-3">Order</th><th className="p-3">Product</th><th className="p-3">Amount</th><th className="p-3">Payment ref</th><th className="p-3">Status</th><th className="p-3">Created</th><th className="p-3"></th></tr></thead><tbody>{(orders||[]).map((o:any)=><tr key={o.id} className="border-t border-slate-800"><td className="p-3 font-mono font-bold">{o.order_number}</td><td className="p-3">{o.order_items?.[0]?.product_name||"-"}</td><td className="p-3">{money(o.total_bdt)}</td><td className="p-3 font-mono">{o.payments?.[0]?.reference||"-"}</td><td className="p-3"><span className="badge text-sky-300">{o.status.replaceAll("_"," ")}</span></td><td className="p-3">{new Date(o.created_at).toLocaleString("en-BD")}</td><td className="p-3"><Link className="text-sky-300 font-bold" href={`/admin/orders/${o.id}`}>Open</Link></td></tr>)}</tbody></table></div>{!orders?.length&&<div className="mt-5"><EmptyState title="No orders found" body="Change the filters or wait for a customer order submission."/></div>}<div className="mt-5 flex items-center justify-between gap-3 text-sm"><p className="muted">{total} matching order{total===1?"":"s"}</p><div className="flex gap-2">{page>1&&<Link className="btn btn-secondary" href={`?q=${encodeURIComponent(p.q||"")}&status=${encodeURIComponent(p.status||"")}&page=${page-1}`}>Previous</Link>}{from+perPage<total&&<Link className="btn btn-secondary" href={`?q=${encodeURIComponent(p.q||"")}&status=${encodeURIComponent(p.status||"")}&page=${page+1}`}>Next</Link>}</div></div></div>
}
