import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getProductBySlug } from "@/lib/data";
import { durationLabel, money } from "@/lib/format";
import { safeEmbedUrl } from "@/lib/video";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const p = await getProductBySlug(slug); return p ? { title: p.name, description: p.description.slice(0,160) } : { title: "Product not found" }; }
export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const product = await getProductBySlug(slug); if (!product) notFound();
  const available = product.available && (product.stock === null || product.stock > 0); const embed = safeEmbedUrl(product.trailer_url);
  return <div className="container py-14"><div className="grid gap-8 lg:grid-cols-[1.15fr_.85fr]">
    <div><div className="relative aspect-[16/10] overflow-hidden border border-slate-800 bg-slate-950">{product.image_url ? <Image src={product.image_url} alt={`${product.name} artwork`} fill priority sizes="(max-width:1024px) 100vw, 58vw" className="object-cover"/> : <div className="absolute inset-0 grid place-items-center text-center"><div><p className="eyebrow">{product.platform?.name}</p><h2 className="mt-2 text-3xl font-black">{product.name}</h2></div></div>}</div>{embed && <div className="mt-5 aspect-video overflow-hidden border border-slate-800"><iframe className="h-full w-full" src={embed} title={`${product.name} trailer`} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen loading="lazy"/></div>}</div>
    <aside className="surface h-fit p-6 sm:p-8"><p className="eyebrow">{product.platform?.name} · {product.account_type}</p><h1 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">{product.name}</h1><p className="muted mt-4 whitespace-pre-line leading-7">{product.description}</p>{product.genre?.length ? <div className="mt-5 flex flex-wrap gap-2">{product.genre.map(g=><span key={g} className="badge text-slate-300">{g}</span>)}</div> : null}<div className="my-7 hr"/><dl className="grid grid-cols-2 gap-5 text-sm"><div><dt className="muted">Access</dt><dd className="mt-1 font-extrabold capitalize">{product.account_type} · {product.kind}</dd></div><div><dt className="muted">Duration</dt><dd className="mt-1 font-extrabold">{durationLabel(product.duration_value, product.duration_unit)}</dd></div><div><dt className="muted">Price</dt><dd className="mt-1 text-xl font-black">{money(product.price_bdt)}</dd></div><div><dt className="muted">Availability</dt><dd className={`mt-1 font-extrabold ${available ? "text-emerald-300" : "text-red-300"}`}>{available ? "Available" : "Unavailable"}</dd></div></dl>{product.customer_instructions && <div className="mt-6 border border-slate-800 bg-slate-950/60 p-4"><p className="text-xs font-extrabold uppercase tracking-wider text-slate-400">Product information</p><p className="muted mt-2 whitespace-pre-line text-sm leading-6">{product.customer_instructions}</p></div>}<Link aria-disabled={!available} className={`btn mt-7 w-full ${available ? "btn-primary" : "btn-secondary pointer-events-none opacity-50"}`} href={available ? `/checkout/${product.slug}` : "#"}>{available ? "Purchase" : "Currently unavailable"}</Link><p className="muted mt-3 text-xs leading-5">Payment is submitted for manual verification. Digital Buy does not mark bKash or Nagad payments as verified until an administrator confirms them.</p></aside>
  </div></div>;
}
